version: '3'

services:
  postgresql:
    container_name: postgresql
    image: postgres:14
    environment:
      - POSTGRES_USER=EuphoriaV
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=scrapper
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - backend

  liquibase-migrations:
    container_name: liquibase
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=EuphoriaV
      - --password=1234
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

networks:
  backend:
    driver: bridge