name: Build bot

on:
  push:
    paths:
      - 'bot/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build bot app
        run: mvn package -pl bot -am

      - name: Build Docker image
        run: docker build -f bot.Dockerfile -t ${{ github.repository }}:${{ env.IMAGE_NAME }} .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ${{ end.REGISTRY }}/${{ github.repository }}:${{ env.IMAGE_NAME }}