name: Build Bot App
on:
  push:
    paths:
      - 'bot/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Bot App
        run: mvn package -pl bot -am