name: Build bot app
on:
  push:
    paths:
      - 'bot/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: see me
        run: echo ${{ github.actor }}
      - name: see token
        run: echo ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build bot app
        run: mvn package -pl bot -am
      - name: Build bot image
        run: docker build -f bot.Dockerfile -t bot .