name: Build scrapper

on:
  push:
    paths:
      - 'scrapper/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: scrapper
  LOWERCASE_AUTHOR: euphoriav
  LOWERCASE_REPOSITORY: tinkoff-java-backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build scrapper app
        run: mvn package -pl scrapper -am

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ env.LOWERCASE_AUTHOR }}/${{ env.LOWERCASE_REPOSITORY }}:${{ env.IMAGE_NAME }}
          file: ./scrapper.Dockerfile

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.LOWERCASE_AUTHOR }}/${{ env.LOWERCASE_REPOSITORY }}:${{ env.IMAGE_NAME }}
          file: ./scrapper.Dockerfile