name: Build scrapper app
on:
  push:
    paths:
      - 'scrapper/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build scrapper app
        run: mvn package -pl scrapper -am
      - name: Build scrapper image
        run: docker build -f scrapper.Dockerfile -t scrapper .